---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: subscription-svc
  name: subscription-svc
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: subscription-svc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: subscription-svc
    spec:
      containers:
      - image: subscription-svc:v1
        imagePullPolicy: IfNotPresent
        name: subscription-svc
        ports:
        - containerPort: 3000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: subscription-svc
  name: subscription-svc
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    run: subscription-svc
  sessionAffinity: None
  type: ClusterIP