---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: payment-svc
  name: payment-svc
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: payment-svc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: payment-svc
    spec:
      containers:
      - image: payment-service:1.0
        imagePullPolicy: IfNotPresent
        name: payment-service
        ports:
        - containerPort: 3000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: payment-svc
  name: payment-svc
  namespace: default
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  fws-payment_mapping
      prefix: /payment/
      rewrite: /api/payment/
      service: payment-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    run: payment-svc
  sessionAffinity: None
  type: ClusterIP